
  CREATE TABLE CONTENTBOARD (
    "IDX" NUMBER(*,0) NOT NULL, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL, 
	"GENRE" VARCHAR2(200 BYTE) NOT NULL, 
	"COMPANY" VARCHAR2(200 BYTE), 
	"CLS" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"RELEASEDATE" VARCHAR2(2000 BYTE) NOT NULL, 
	"PLATFORM" VARCHAR2(2000 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"PHOTO" VARCHAR2(2000 BYTE), 
	"SUBJECT" VARCHAR2(2000 BYTE) NOT NULL
   );
delete from CONTENTBOARD;
drop sequence CONTENTBOARD_idx_seq;
create sequence CONTENTBOARD_idx_seq;
commit;


 CREATE TABLE CONTENTBOARD_comment (
    "IDX" NUMBER(*,0) NOT NULL, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL, 
	"GENRE" VARCHAR2(200 BYTE) NOT NULL, 
	"COMPANY" VARCHAR2(200 BYTE), 
	"CLS" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"RELEASEDATE" VARCHAR2(2000 BYTE) NOT NULL, 
	"PLATFORM" VARCHAR2(2000 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"PHOTO" VARCHAR2(2000 BYTE), 
	"SUBJECT" VARCHAR2(2000 BYTE) NOT NULL,
   );